#ifndef __JDARCHIVECOMMDEF_H__
#define __JDARCHIVECOMMDEF_H__

#define JDARCHIVE_SERVER_PORT		(11709) // Server port

// Server response error code
enum 
{
	JDRESPONSE_SUCCESS = 0,
	JDRESPONSE_INTERNAL_ERROR,
	JDRESPONSE_DATA_ERROR,
	JDRESPONSE_DENY,
	JDRESPONSE_LOGIN_FAIL,
	JDRESPONSE_ALREADY_EXISTS,
	JDRESPONSE_NOT_EXISTS,
	JDRESPONSE_PARENT_NOT_EXISTS,
	JDRESPONSE_TARGET_NOT_EMPTY,
	JDRESPONSE_USER_ABORT,
	JDRESPONSE_VER_ALREADY_CHECKED,
	JDRESPONSE_VER_NOT_CHECKED,
	JDRESPONSE_VER_ALREADY_DELETED,
	JDRESPONSE_VER_VERSION_ERROR,
	JDRESPONSE_NAME_CONFLICTS,
	JDRESPONSE_FILE_LOCKED,
	JDRESPONSE_RECOVERY_DATA_NOTFOUND,
	JDRESPONSE_CLIENT_VER,
};

// Privilege
enum 
{
	JDPRIV_DIABLED = 0,
	JDPRIV_USER,
	JDPRIV_POWER_USER,
	JDPRIV_SUPERVISOR,
	JDPRIV_ADMIN,
	JDPRIV_SUPER_ADMIN,
};

static const LPCTSTR _PRIVILEGES[] = {
	_T("已禁用"),
	_T("普通用户"),
	_T("高级用户"),
	_T("部门主管"),
	_T("系统管理员"),
	_T("超级管理员"),
};

#define _PRIVILEGES_COUNT	(sizeof(_PRIVILEGES) / sizeof(LPCTSTR))

// action targets
enum {
	JD_ACTION_NONE = 0,
	JD_ACTION_ROLE,	
	JD_ACTION_USER,
	JD_ACTION_CAT,
	JD_ACTION_FILE,
	JD_ACTION_VER,
	JD_ACTION_RECOVABLE,
	JD_ACTION_FILESYSTEM_FOLDER,
	JD_ACTION_FILESYSTEM_FILE,
};

enum {

	JD_PACKET_HEARTBEAT = 32,
	JD_PACKET_LOGIN,
	JD_PACKET_CHANGE_PASSWORD,

	// User administration
	JD_PACKET_USER_LIST,
	JD_PACKET_USER_ADD,
	JD_PACKET_USER_CHANGE,
	JD_PACKET_USER_RESETPASSWORD,

	JD_PACKET_ROLE_LIST,
	JD_PACKET_ROLE_ADD,
	JD_PACKET_ROLE_CHANGE,

	JD_PACKET_CAT_LIST,
	JD_PACKET_CAT_ADD,
	JD_PACKET_CAT_CHANGE,
	JD_PACKET_CAT_DELETE,
	JD_PACKET_CAT_ROOT,

	JD_PACKET_FILE_LIST,
	JD_PACKET_FILE_ADD,
	JD_PACKET_FILE_DELETE,
	JD_PACKET_FILE_MANAGE_VER_REQUEST,
	JD_PACKET_FILE_MANAGE_VER_APPLY,
	
	JD_PACKET_VER_LIST,
	JD_PACKET_VER_CHECK,
	JD_PACKET_VER_UNCHECK,
	JD_PACKET_VER_DELETE,

	JD_PACKET_VER_DOWNLOAD,
	JD_PACKET_VER_DOWNLOAD_DATA_BEGIN, // client -> server

	JD_PACKET_REQUEST_UPLOAD_VER,
	JD_PACKET_CANCEL_REQUEST_UPLOAD_VER,
	JD_PACKET_VER_UPLOAD,

	OBSOLETE_JD_PACKET_ACTION_LIST, // Obsoleted since 1.20
	JD_PACKET_REQUEST_USER,
	JD_PACKET_REQUEST_ROLE,
	JD_PACKET_REQUEST_CAT,
	JD_PACKET_REQUEST_FILE,
	JD_PACKET_REQUEST_VER,	

	JD_PACKET_CHECK_UPDATE,
	JD_PACKET_UPDATE_DOWNLOAD,
	JD_PACKET_UPLOAD_APP,
	JD_PACKET_UPLOAD_APP_RESULT,

	OBSOLETE_JD_PACKET_DBCLEANUP, // Obsoleted since 1.21

	JD_PACKET_CAT_INIT_START,
	JD_PACKET_CAT_INIT_CAT,
	JD_PACKET_CAT_INIT_FILE,
	JD_PACKET_CAT_INIT_FILE_OK,
	JD_PACKET_CAT_INIT_END,
	
	JD_PACKET_PASTE_FILE,
	JD_PACKET_PASTE_CAT,

	JD_PACKET_DATA_RECOVERY_LIST,
	JD_PACKET_RECOVERY,
	JD_PACKET_RECOVERY_DOWNLOAD,

	JD_PACKET_CAT_CHANGE_PRIV,
	JD_PACKET_DELTREE,

	JD_PACKET_FILESYSTEM_REQUEST,
	JD_PACKET_FILESYSTEM_NEXT,
	JD_PACKET_FILESYSTEM_FINISH,

	JD_PACKET_DEFINE_END, // End of packet definition
};

#endif // __JDARCHIVECOMMDEF_H__